export_preferences:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: terrestream_local
import_preferences:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: terrestream_local
    profile:
      required: true
      selector:
        object:
